baseURL: https://hesusruiz.github.io/
languageCode: en-us
title: Jesus Ruiz

theme: "PaperMod"

params:
    homeInfoParams:
        Title: About blockchain for the real world
        Content: Some thoughts about blockchain technology for the real economy, versus the financial economy.

    socialIcons: # optional
        - name: "Linkedin"
          url: "https://www.linkedin.com/in/jesus-ruiz-martinez/"
    ShowShareButtons: true
    ShowToc: true
    ShowBreadCrumbs: true

buildDrafts: true
